Add new theme (scratch-dark) and allow for a secret theme to be enabled randomly
jeffalo/ocular pull request #127
Opened 2021-12-09 03:58 UTC by ScolderCreations

Should probably be tested, because I didn’t test it myself.

2021-12-09 08:45 UTC, return-misaPuding commented
Cool! I don't know Vue tho, so I can't check it :(

2021-12-26 08:36 UTC, jeffalo commented
what's up with the random stuff?

2021-12-26 21:33 UTC, return-misaPuding requested changes

2021-12-26 21:33 UTC, return-misaPuding commented on components/Footer.vue
>        let themes = ['system', 'light', 'dark', 'scratch', 'scratch-dark', 'catsunited' , 'classic-dark']
The 'missing-glasses' theme was apparently wiped out by jeffalo after april fools, so if this actually gets merged it will probably add a random chance to break something :(

2022-01-14 16:52 UTC, jeffalo commented
thanks i appreciate the theme, but it will take some time to test and make sure its all good.

thanks for your patience!

2025-03-31 17:52 UTC, closed without merging