allow “undefined” to be searched
jeffalo/ocular pull request #136
Opened 2022-01-10 19:46 UTC by ScolderCreations

should solve #130

2022-01-14 16:51 UTC, jeffalo commented
have you tested this?

2022-01-15 02:53 UTC, ScolderCreations commented
> thank you! have you tested this?

no, sadly my computer corrupted before i got the opportunity to :(

2022-01-16 16:04 UTC, pufferfish101007 requested changes
At the moment it doesn't look like this will actually fix anything - I've left a couple of comments.

2022-01-16 16:04 UTC, pufferfish101007 commented on pages/search.vue
> +    if (this.search !=== undefined) {
This is incorrect javascript. `!==` is a strict inequality check, the opposite of `===`, `!=` is the opposite of `==`. Also, you'll want to be comparing `this.$route.query.q` rather than `this.search` as `this.search` will always be a string.

2022-01-16 16:04 UTC, pufferfish101007 commented on pages/search.vue
> +      search: encodeURIComponent(decodeURIComponent(String(this.$route.query.q))),
Why is this needed? `this.$route.query.q` will always be either a string or `undefined`, and it will yield the same result whether it's `"undefined"` or `undefined`.

2022-01-18 02:10 UTC, ScolderCreations commented on pages/search.vue
> +    if (this.search !=== undefined) {
Whoops. I’ll fix that.

2022-01-31 02:55 UTC, hello-smile6 approved these changes
Good!

2022-07-30 22:58 UTC, Chameleon-Coder approved these changes
It's awesome!

2022-07-31 08:14 UTC, Weredime commented
@Chameleon-Coder have you actually tested this PR?

2022-07-31 11:35 UTC, Chameleon-Coder commented
@Weredime No, just agreeing with @hello-smile6. Why do you need to ask that?

2022-08-05 17:48 UTC, ScolderCreations commented
> No, just agreeing with @hello-smile6. Why do you need to ask that?

I’m assuming they believe it is perhaps silly to say something is awesome when you haven’t even tried it yet… I can understand that.

2024-08-07 13:18 UTC, mxmou commented
The bug was fixed by d8f89bb.

2024-08-15 19:35 UTC, closed without merging